### PR TITLE
Add some awesome resources

### PR DESCRIPTION
**Pull request by tomek-he-him**
By @staltz, both of them.

### CODE REVIEW

**Comment by stoeffel** [comment]
Hmm... I added the introrx gist earlier and @staltz pointed out that it is an intro to reactive programming and not functional rp. But I still think its a good read and would fit right into this list. So I will merge it anyway.

**Comment by tomek-he-him** [comment]
Yeah, but as @staltz [rightfully points out](https://medium.com/@andrestaltz/why-i-cannot-say-frp-but-i-just-did-d5ffaa23973b), FRP is the very flavor of reactive programming which he advocates in the gist!

**Comment by stoeffel** [comment]
Yop. Btw I added you as a collaborator. Feel free to add stuff if you like.

**Comment by tomek-he-him** [comment]
Thanks! :)

**Comment by tomek-he-him** [comment]
:beers:

**Pull request merged**
